recipe: default.v1
language: en

assistant_id: basic_tutorial_money_transfer

pipeline:
  - name: CompactLLMCommandGenerator
    llm:
      provider: self-hosted
      model: meta-llama/Meta-Llama-3.1-8B-Instruct
      api_base: "http://localhost:8000/v1"
      temperature: 0.1
      max_tokens: 256
      timeout: 30

policies:
  - name: FlowPolicy