recipe: default.v1
language: en

assistant_id: basic_tutorial_money_transfer

pipeline:
  - name: CompactLLMCommandGenerator
    llm:
      provider: azure
      model: gpt-4o
      api_base: ${AZURE_OPENAI_ENDPOINT}
      api_version: "2024-02-15-preview"
      temperature: 0.1
      max_tokens: 256
      timeout: 10

policies:
  - name: FlowPolicy