[build-system]
requires = ["hatchling>=1.18.0"]
build-backend = "hatchling.build"

[project]
name = "basic-tutorial"
version = "0.1.0"
description = "Basic money transfer assistant tutorial"
requires-python = ">=3.10,<3.12"
dependencies = [
    "rasa-pro>=3.8.0",
    "rasa-sdk>=3.8.0",
    "openai>=1.0.0",
]

[project.optional-dependencies]
azure = [
    "azure-cognitiveservices-speech>=1.30.0",
]
test = [
    "pytest>=7.0.0",
    "pytest-asyncio>=0.21.0",
]

# Build configuration for recipe collection
[tool.hatch.build.targets.wheel]
include = [
    "*.yml",
    "*.yaml", 
    "*.md",
    "data/**/*",
    "actions/**/*",
    "tests/**/*",
    "conversations/**/*"
]

[tool.ruff]
line-length = 88
target-version = "py310"

[tool.pytest.ini_options]
testpaths = ["tests"]
markers = [
    "integration: marks tests as integration tests",
]